use user01;

-- 회원 테이블 생성
CREATE TABLE MEMBERS (
    USERNAME VARCHAR(255) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(255),
    BIRTH DATE,
    ACCOUNT_NON_EXPIRED BOOLEAN,
    ACCOUNT_NON_LOCKED BOOLEAN,
    CREDENTIALS_NON_EXPIRED BOOLEAN,
    ENABLED BOOLEAN
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- 공지사항 테이블 생성
CREATE TABLE `NOTICE` (
	`BOARD_NUM`	BIGINT	NOT NULL auto_increment PRIMARY KEY,
	`BOARD_TITLE`	VARCHAR(255)	NULL,
	`BOARD_CONTENTS`	LONGTEXT	NULL,
	`BOARD_WRITER`	VARCHAR(255)	NULL,
	`BOARD_DATE`	DATETIME	NULL,
	`BOARD_HIT`	BIGINT	NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;

-- 공지파일첨부 테이블 생성
CREATE TABLE `NOTICEFILES` (
	`FILE_NUM`	BIGINT	NOT NULL auto_increment PRIMARY KEY,
	`ORI_NAME`	VARCHAR(255)	NULL,
	`SAVE_NAME`	VARCHAR(255)	NULL,
	`BOARD_NUM`	BIGINT,
    FOREIGN KEY (`BOARD_NUM`) REFERENCES `NOTICE` (`BOARD_NUM`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;


-- 공지사항 임의의 데이터 insert
INSERT INTO `NOTICE` 
(`BOARD_TITLE`, `BOARD_CONTENTS`, `BOARD_WRITER`, `BOARD_DATE`, `BOARD_HIT`)
VALUES
('첫 번째 공지', '첫 번째 공지 내용입니다.', '관리자', NOW(), 0),
('두 번째 공지', '두 번째 공지 내용입니다.', '운영팀', NOW(), 5);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`BOARD_NUM`
);

-- 질문답변 테이블 생성
CREATE TABLE `QNA` (
	`BOARD_NUM`	BIGINT	NOT NULL auto_increment PRIMARY KEY,
	`BOARD_TITLE`	VARCHAR(255)	NULL,
	`BOARD_CONTENTS`	LONGTEXT	NULL,
	`BOARD_WRITER`	VARCHAR(255)	NULL,
	`BOARD_DATE`	DATETIME	NULL,
	`BOARD_HIT`	BIGINT	NULL,
    `BOARD_REF`	BIGINT	NULL,
    `BOARD_STEP`	BIGINT	NULL,
    `BOARD_DEPTH`	BIGINT	NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;

-- QNA 임의의 데이터 insert
INSERT INTO `QNA`
(`BOARD_TITLE`, `BOARD_CONTENTS`, `BOARD_WRITER`, `BOARD_DATE`, `BOARD_HIT`, `BOARD_REF`, `BOARD_STEP`, `BOARD_DEPTH`)
VALUES
('첫 번째 질문', '첫 번째 질문 내용입니다.', 'user1', NOW(), 0, 1, 0, 0),
('두 번째 질문', '두 번째 질문 내용입니다.', 'user2', NOW(), 3, 2, 0, 0);


-- 질문답변첨부파일 테이블 생성
CREATE TABLE `QNAFILES` (
	`FILE_NUM`	BIGINT	NOT NULL auto_increment PRIMARY KEY,
	`ORI_NAME`	VARCHAR(255)	NULL,
	`SAVE_NAME`	VARCHAR(255)	NULL,
	`BOARD_NUM`	BIGINT,
    FOREIGN KEY (`BOARD_NUM`) REFERENCES `QNA` (`BOARD_NUM`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;

-- 상품정보 테이블 생성
CREATE TABLE `PRODUCTS`(
	`PRODUCT_NUM` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `PRODUCT_NAME` VARCHAR(255) NULL,
    `PRODUCT_CONTENTS` LONGTEXT NULL,
    `PRODUCT_DATE` DATETIME NULL,
    `PRODUCT_RATE` DECIMAL(4,2) NULL,
    `KIND_NUM` BIGINT NOT NULL,
	FOREIGN KEY (`KIND_NUM`) REFERENCES `PRODUCTS_KIND` (`KIND_NUM`)
)
ENGINE = InnoDBnoticefilesprofileORI_NAMESAVE_NAME
DEFAULT CHARACTER SET = utf8mb4
;

-- 상품종류 테이블 생성
CREATE TABLE `PRODUCTS_KIND` (
	`KIND_NUM` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `KIND_NAME` VARCHAR(255) NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;


-- 상품종류 테이블 insert
INSERT INTO PRODUCTS_KIND VALUES(1, "예금");
INSERT INTO PRODUCTS_KIND VALUES(2, "적금");
INSERT INTO PRODUCTS_KIND VALUES(3, "대출");

-- 프로필 테이블 생성
CREATE TABLE PROFILE (
    USERNAME VARCHAR(255) NOT NULL PRIMARY KEY,
    SAVE_NAME VARCHAR(255) NOT NULL,
    ORI_NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES MEMBERS (USERNAME)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;



-- 권한 테이블 생성
CREATE TABLE ROLE (
    ROLE_NUM BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME VARCHAR(255) NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- 멤버권한 테이블 생성
CREATE TABLE MEMBER_ROLE (
    USERNAME VARCHAR(255) NOT NULL,
    ROLE_NUM BIGINT NOT NULL,
    PRIMARY KEY (USERNAME, ROLE_NUM),
    FOREIGN KEY (USERNAME) REFERENCES MEMBERS (USERNAME),
    FOREIGN KEY (ROLE_NUM) REFERENCES ROLE (ROLE_NUM)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- ROLE
-- ROLE_ADMIN
-- ROLE_MANAGER
-- ROLE_MEMBER

-- 권한 insert
INSERT INTO ROLE VALUES(null, 'ROLE_ADMIN');
INSERT INTO ROLE VALUES(null, 'ROLE_MANAGER');
INSERT INTO ROLE VALUES(null, 'ROLE_MEMBER');

-- 장바구니 테이블 생성
CREATE TABLE CART (
	USERNAME VARCHAR(255) NOT NULL,
    PRODUCT_NUM BIGINT NOT NULL,
    PRIMARY KEY (USERNAME, PRODUCT_NUM),
    FOREIGN KEY (USERNAME) REFERENCES MEMBERS (USERNAME),
    FOREIGN KEY (PRODUCT_NUM) REFERENCES PRODUCTS (PRODUCT_NUM)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- 회원정보와 프로필 사진 정보 조인(프로필 없는 회원도 조인 가능)
SELECT M.USERNAME, M.NAME, M.EMAIL, M.PHONE, P.SAVE_NAME, P.ORINAME
FROM MEMBERS M LEFT JOIN PROFILE P ON M.USERNAME = P.USERNAME;

-- 한 회원이 가진 모든 권한 조인
SELECT M.USERNAME, M.NAME, R.ROLE_NAME
FROM MEMBERS M JOIN MEMBER_ROLE MR ON M.USERNAME = MR.USERNAME
JOIN ROLE R ON MR.ROLE_NUM = R.ROLE_NUM;

-- 회원의 기본정보, 프로필, 권한 조인
SELECT M.*, P.*, R.*
FROM MEMBERS M
INNER JOIN PROFILE P USING (USERNAME) 
INNER JOIN MEMBER_ROLE MR USING(USERNAME)
INNER JOIN ROLE R USING(ROLE_NUM)
 WHERE USERNAME = 3;


show tables;

-- 가입정보 테이블 생성
CREATE TABLE ACCOUNT (
	ACCOUNT_NUM VARCHAR(255) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(255),
    PRODUCT_NUM BIGINT,
    ACCOUNT_DATE DATE,
	ACCOUNT_BALANCE BIGINT,
    FOREIGN KEY (USERNAME) REFERENCES MEMBERS (USERNAME),
    FOREIGN KEY (PRODUCT_NUM) REFERENCES PRODUCTS (PRODUCT_NUM)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SELECT * FROM ACCOUNT;
